axonivy/project-build-plugin

src/main/java/ch/ivyteam/ivy/maven/DeployToEngineMojo.java, src/main/java/ch/ivyteam/ivy/maven/engine/deploy/dir/FileDeployer.java, src/main/java/ch/ivyteam/ivy/maven/engine/deploy/http/HttpDeployer.java
- Streamline the output of the deployment methods
- Improve warning messages
=> XIVY-623 Streamline output of FileDeployer and HttpDeployer

src/main/java/ch/ivyteam/ivy/maven/InstallEngineMojo.java
- clarify doc
- fix expected artifact descriptor
=> XIVY-3255 review: re-word and fix documentation of new maven downloader

src/main/java/ch/ivyteam/ivy/maven/engine/MavenProjectBuilderProxy.java
https://zugprojenkins/job/project-build-plugin/job/feature%252FXIVY-3371-projectBuildPlugin-j11/
=> XIVY-3334 refactor: migrate deprecated jdk api

src/site/apt/faq.apt, src/site/site.xml
- to ease access to jdk version specific issues.
=> XIVY-3383 link Q&A on the project-build-plugin site

src/main/java/ch/ivyteam/ivy/maven/DeployToEngineMojo.java, src/main/java/ch/ivyteam/ivy/maven/InstallEngineMojo.java
- streamline demo versions to 8.0.0
=> XIVY-3371 improve: mojo doc

src/test/java/ch/ivyteam/ivy/maven/BaseEngineProjectMojoTest.java
- keep builds stable in same LTS / LE train: no need to touch
infrastructure if nothing changed but the version of our product.
- exclude next major version to prevent test against too recent new
engines.
BUILD: https://zugprojenkins/job/project-build-plugin/job/feature%252FXIVY-3469-infra-for-new-versions/
=> XIVY-3469 allow newer versions with same major

src/test/java/ch/ivyteam/ivy/maven/TestDeployToEngineMojo.java, src/test/java/ch/ivyteam/ivy/maven/TestDeployToRunningEngine.java
- set a fixed 'deployToEngineApplication'
=> XIVY-3479 adjust deploy tests to new mandatory property

Jenkinsfile, pom.xml
=> Never deploy to internal artifactory

Jenkinsfile
Build: https://jenkins.ivyteam.io/job/project-build-plugin/job/bugfix%252Fdeploy_only_on_master/
=> Only deploy snapshot if it was built on master

src/main/java/ch/ivyteam/ivy/maven/AbstractEngineMojo.java, src/main/java/ch/ivyteam/ivy/maven/CompileProjectMojo.java, src/main/java/ch/ivyteam/ivy/maven/engine/MavenProjectBuilderProxy.java, src/main/java/ch/ivyteam/ivy/maven/engine/Slf4jSimpleEngineProperties.java, src/test/java/ch/ivyteam/ivy/maven/TestSlf4jWarningConfiguration.java
Jenkins: https://jenkins.ivyteam.io/job/project-build-plugin/job/feature%252FXIVY-3123-merge-validation/
=> XIVY-3123 Pass iar dependencies to core to enable validation

pom.xml, src/main/java/ch/ivyteam/ivy/maven/AbstractProjectCompileMojo.java
Build: https://jenkins.ivyteam.io/job/project-build-plugin/job/feature%252FXIVY-3138_prepare-8.0.3-release/
Preparations for 8.0.3 release. Will merge & release as soon as I have confirmation that the new stuff works.
=> XIVY-3138 Increase plugin version to 8.0.3

src/main/java/ch/ivyteam/ivy/maven/StartTestEngineMojo.java
Build: https://jenkins.ivyteam.io/job/project-build-plugin/job/feature%252FXIVY-2275_url_property/
=> XIVY-2275 Describe the test.engine.url property

src/main/java/ch/ivyteam/ivy/maven/StopTestEngineMojo.java, src/test/java/ch/ivyteam/ivy/maven/TestEngineControlEngineDirectory.java
Build: https://jenkins.ivyteam.io/job/project-build-plugin/job/bugfix%252FXIVY-2275_check_null/
=> XIVY-2275 Make stop engine mojo null safe

Jenkinsfile
=> use 'master' commits but not it's jenkinsfile

src/main/java/ch/ivyteam/ivy/maven/AbstractProjectCompileMojo.java, src/main/java/ch/ivyteam/ivy/maven/SetupIvyTestPropertiesMojo.java, src/main/java/ch/ivyteam/ivy/maven/bpm/test/IvyTestRuntime.java, src/main/java/ch/ivyteam/ivy/maven/util/MavenRuntime.java, src/test/java/ch/ivyteam/ivy/maven/TestSetupIvyTestPropertiesMojo.java
- using test context resource
- resolve form repo
=> XIVY-3565 share projects to deploy via project.locations property

src/main/java/ch/ivyteam/ivy/maven/StartTestEngineMojo.java, src/test/java/ch/ivyteam/ivy/maven/TestStartEngine.java
Build: https://jenkins.ivyteam.io/job/project-build-plugin/job/bugfix%252FXIVY-3773_copy_engine_permissions_8.0/
Same fix for 8.0
=> Bugfix/xivy 3773 copy engine permissions 8.0

src/test/resources/base/src_test/ch/ivyteam/test/TestMyBean.java
https://jenkins.ivyteam.io/view/scrum-master/job/project-build-plugin/job/feature%252Ffix_validation/
=> remove unneeded import

src/main/java/ch/ivyteam/ivy/maven/SetupIntegrationTestPropertiesMojo.java, src/main/java/ch/ivyteam/ivy/maven/SetupIvyTestPropertiesMojo.java, src/main/java/ch/ivyteam/ivy/maven/StartTestEngineMojo.java
my last change before starting the release process for 9.1 :)
=> XIVY-622 review: clarify & streamline goal docs

src/main/java/ch/ivyteam/ivy/maven/engine/EngineControl.java, src/main/java/ch/ivyteam/ivy/maven/engine/EngineModuleHints.java
added --add-opens hints for forked  integration-test JVM
... now for the LTS release train
=> XIVY-4413 Reflection access warnings in maven builds

README.md, pom.xml, src/main/java/ch/ivyteam/ivy/maven/AbstractEngineMojo.java, src/main/java/ch/ivyteam/ivy/maven/MavenDependencyMojo.java
- change default ivy version to 9.2.0
- improve maven-dependency goal description
=> Fix GitHub pages build

src/main/java/ch/ivyteam/ivy/maven/MavenDependencyMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/AbstractEngineInstanceMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/AbstractProjectCompileMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/CompileProjectMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/CompileTestProjectMojo.java, src/test/java/ch/ivyteam/ivy/maven/compile/CompileMojoRule.java
- we will not necessarily need any of the standard compile params for
openApi codegen
=> refactor: abstract mojo with ivyEngine access; excluding compile params

pom.xml
- being the LTS on Ubuntu, it should be find to rais it now
=> raise maven-core plugins to 3.6.3

build/release/Jenkinsfile
we'll have here some try-and-error. sorry for that.
=> Fix release pipeline (substitution

pom.xml
Prepare for next development cycle (release/10.0)
=> Prepare for next development cycle (release/10.0)

src/test/java/ch/ivyteam/ivy/maven/TestDeployToRunningEngine.java
- re-use the URL where the engine actually started, instead of assuming defaults (port is may different if other engines are running concurrently)
- provide more log output on whats going on
=> stabilize: re-use hardened test-infra from LTS10 branch

pom.xml
Prepare for next development cycle (release/11.2)
=> Prepare for next development cycle (release/11.2)

src/main/java/ch/ivyteam/ivy/maven/AbstractEngineMojo.java, src/main/java/ch/ivyteam/ivy/maven/engine/download/LatestMinorVersionRange.java, src/test/java/ch/ivyteam/ivy/maven/engine/download/TestLatestMinorVersionRange.java
will be applied to our builds and merged to 11.2
=> XIVY-9799 Add option that plugin can download latest minor version

src/main/java/ch/ivyteam/ivy/maven/engine/OsgiRuntime.java
=> XIVY-8973 Add pacakges to bootdelegation for jdt compiler

src/main/java/ch/ivyteam/ivy/maven/IarPackagingMojo.java, src/test/java/ch/ivyteam/ivy/maven/TestIarPackagingMojo.java, src/test/resources/base/.project
change the default includes, so that `target/src_hd` is within the packed IAR: https://github.com/axonivy/core/commit/57f84609f77c3086c36d04ad8666980fadcbfff0
=> XIVY-13627 include 'target/src_hd' by default

pom.xml
Prepare for next development cycle (release/11.3)
=> Prepare for next development cycle (release/11.3)

.github/release-drafter.yml, .github/workflows/release-drafter.yml
introducing release-drafter: will only work after integration on master
=> XIVY-14222 introduce release-drafter

README.md
Document the release publishing as manual step ... we can later still opt to automate this if we like
=> document; how to publish draft-release

src/main/java/ch/ivyteam/ivy/maven/engine/EngineModuleHints.java
=> XIVY-9730 Remove fallback for old jvm-module.options location

pom.xml
engine-integration-test and selenium tests are failing.
=> XIVY-14570 Add plexus sec dispatcher to fix consuming builds

src/main/java/ch/ivyteam/ivy/maven/ShareEngineCoreClasspathMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/AbstractEngineInstanceMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/CompileProjectMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/CompileTestProjectMojo.java, src/main/java/ch/ivyteam/ivy/maven/engine/EngineClassLoaderFactory.java, src/main/java/ch/ivyteam/ivy/maven/engine/EngineMojoContext.java, src/main/java/ch/ivyteam/ivy/maven/engine/MavenProjectBuilderProxy.java, src/main/java/ch/ivyteam/ivy/maven/test/SetupIvyTestPropertiesMojo.java, src/main/java/ch/ivyteam/ivy/maven/util/ClasspathJar.java, src/test/java/ch/ivyteam/ivy/maven/BaseEngineProjectMojoTest.java, src/test/java/ch/ivyteam/ivy/maven/TestLoggerIntegration.java, src/test/java/ch/ivyteam/ivy/maven/engine/TestClasspathJar.java, src/test/java/ch/ivyteam/ivy/maven/test/TestSetupIvyTestPropertiesMojo.java
I'll investigate in the next cool stuff. Troubles when converting Path<>URI and stuff like that.
=> Revert some java.nio because of troubles with windows

src/main/java/ch/ivyteam/ivy/maven/engine/EngineControl.java, src/main/java/ch/ivyteam/ivy/maven/engine/EngineVmOptions.java, src/main/java/ch/ivyteam/ivy/maven/test/StartTestEngineMojo.java, src/main/java/ch/ivyteam/ivy/maven/test/StopTestEngineMojo.java
=> Deprecate additionalVmOptions in favor of additionalVmArgs

pom.xml, src/site/site.xml
fix the build warnings:
- migrate from project->site xml
- update doxia plugin-doc renderer
- use maven-plugin-report-plugin which still contains the 'report' goal
=> fix-site-warning

.github/release-drafter-lts12.yml
allow release-drafts per branch; as documented here https://github.com/release-drafter/release-drafter/issues/656#issuecomment-806184887
=> Separate release-draft templates for leading-edge and LTS12

README.md
I'm sure we can automate more of this stuff; but for now I'm just documenting the things I did to introduce drafts for another LTS train.
=> Document current approach to introduce a new release-drafter template

pom.xml
I think we had also troubles in the past, this is a known workaround for this problem.
At least the build is working again.
=> Fix build while generating site (egit download)

pom.xml
Reverts axonivy/project-build-plugin#528
=> Revert "Fix build while generating site (egit download)"

Jenkinsfile
R12: https://github.com/axonivy/project-build-plugin/pull/544
=> Only update gh pages if has scm changes

src/main/java/ch/ivyteam/ivy/maven/validate/ValidateMojo.java, src/main/resources/META-INF/plexus/components.xml, src/test/java/ch/ivyteam/ivy/maven/validate/TestValidateMojo.java
r12: https://github.com/axonivy/project-build-plugin/pull/543
=> XIVY-10541 Detect different plugin versions

src/main/java/ch/ivyteam/ivy/maven/validate/ValidateMojo.java, src/site/apt/lifecycle.apt.vm
master: https://github.com/axonivy/project-build-plugin/pull/547
=> XIVY-10541 Improve doc for ValidateMojo

pom.xml
Prepare for next development cycle (release/12.0)
=> Prepare for next development cycle (release/12.0)

src/test/resources/pom.xml
https://github.com/axonivy/project-build-plugin/security/code-scanning/1
=> Fix unecessary repository definition in test pom.xml to fix GitHub security issue

renovate.json
another attempt to reach the goal of static predictable commit titles.
=> Attemp to avoid changing renovate PR titles (fix/chore)

.github/renovate.json
https://github.com/axonivy/renovate-config/pull/12
=> refactor: disabled semantic commits are now inherited

src/site/site.xml
address warnings generated by CI ... after upgrading to latest site plugin #616
=> backport: maven plugin upgrades>R10

.github/renovate.json
reduce the noise in my mailbox asking for manual actions
=> renovate: grown up > auto-merge more deps

build/windows/Jenkinsfile
https://1ivy.atlassian.net/browse/XIVY-16584
https://github.com/axonivy/project-build-plugin/pull/682
=> Update build from temurin-jdk-21.0.6.7 to 21.0.7.6

pom.xml
Prepare for next development cycle (release/13.1)
=> Prepare for next development cycle (release/13.1)

pom.xml, src/main/java/ch/ivyteam/ivy/maven/engine/Slf4jSimpleEngineProperties.java, src/test/java/ch/ivyteam/ivy/maven/TestSlf4jWarningConfiguration.java, src/test/java/ch/ivyteam/ivy/maven/compile/TestCompileProjectMojo.java, src/test/resources/base/processes/myWebService.p.json
backporting #700 to release/13.1
=> XIVY-16828 Propagate Process warnings to Maven CLI console

pom.xml, src/main/java/ch/ivyteam/ivy/maven/engine/Slf4jSimpleEngineProperties.java, src/test/java/ch/ivyteam/ivy/maven/TestSlf4jWarningConfiguration.java, src/test/java/ch/ivyteam/ivy/maven/compile/TestCompileProjectMojo.java, src/test/resources/base/processes/myWebService.p.json
backport #700 to release/12 which is also affected
=> XIVY-16828 Process issues not reported as [WARNING] > R12

README.md, build/release/Jenkinsfile, pom.xml, src/site/apt/examples.apt
same approach as in [ivymx](https://github.com/axonivy/ivymx/pull/134)
=> XIVY-16780 switch to Central Portal

src/main/java/ch/ivyteam/ivy/maven/ShareEngineCoreClasspathMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/AbstractEngineInstanceMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/CompileProjectMojo.java, src/main/java/ch/ivyteam/ivy/maven/compile/CompileTestProjectMojo.java, src/main/java/ch/ivyteam/ivy/maven/engine/EngineClassLoaderFactory.java, src/main/java/ch/ivyteam/ivy/maven/engine/MavenProjectBuilderProxy.java, src/main/java/ch/ivyteam/ivy/maven/generate/GenerateDataClassSourcesMojo.java, src/main/java/ch/ivyteam/ivy/maven/generate/GenerateDialogFormSourcesMojo.java, src/main/java/ch/ivyteam/ivy/maven/generate/GenerateWebServiceSourcesMojo.java, src/main/java/ch/ivyteam/ivy/maven/util/ClasspathJar.java, src/test/java/ch/ivyteam/ivy/maven/TestLoggerIntegration.java, src/test/java/ch/ivyteam/ivy/maven/engine/TestClasspathJar.java, src/test/java/ch/ivyteam/ivy/maven/test/TestSetupIvyTestPropertiesMojo.java
related to https://github.com/axonivy/core/pull/9998
=> XIVY-17305 project build: switch file to path

pom.xml
Reverts axonivy/project-build-plugin#824
=> Revert "Update dependency org.codehaus.plexus:plexus-archiver to v4.10.2 (master)"
