axonivy/project-build-plugin

pom.xml
src/main/java/ch/ivyteam/ivy/maven/IarDeployMojo.java

- you can now use ivy:deploy-to-engine instead of
project-build:deploy-to-engine or even worse
com.axonivy.ivy.ci:project-build-plugin:7.4.0:deploy-to-engine

XIVY-623 Use 'ivy' as goal prefix

---

.gitignore

For external contributors using intellij idea it would be great to have the idea
project files in the .gitignore file too.
No issue for that PR.

Add IntellJ idea project files to .gitignore

---

pom.xml

avoid platform dependent build, set project encoding to UTF-8.
see #10
If you don't want like an explicit encoding configuration or want another encoding, just close this PR / issue =)

Explicitly set project encoding to UTF-8

---

pom.xml
src/main/java/ch/ivyteam/ivy/maven/InstallEngineMojo.java
src/test/java/ch/ivyteam/ivy/maven/TestInstallEngineMojo.java

- the newest version correctly preservers file permissions when
unpacking zips. this is at least for elasticsearch/bin (x-flag)
- nice side effect. also axon ivy engine launchers /bin has now correct
file permissions (x-flag)

XIVY-2927 Upgrade to newest zip4j lib

---

.classpath
pom.xml
src/site/site.xml

- simplify maintenance and and streamline the plugin to use the same JDK
as the ivy-core platform
- update maven plugins to be compatible with java 11
BUILD: https://zugprojenkins/job/project-build-plugin/job/feature%252FXIVY-3371-projectBuildPlugin-j11/

XIVY-3334 build with java11

---

src/main/java/ch/ivyteam/ivy/maven/InstallEngineMojo.java

- ease error cause detection by printing the engine dir.
BUILDS: https://zugprojenkins/job/project-build-plugin/job/feature%252FXIVY-3384-exposeUsedEngine/

XIVY-3384 state used engine as info log

---

src/main/java/ch/ivyteam/ivy/maven/InstallEngineMojo.java

XIVY-3384 log engine dir with dated version

---

src/main/java/ch/ivyteam/ivy/maven/DeployToEngineMojo.java

- SYSTEM is a bad default which only leads to confusion, nobody should
use the system app for custom workflows (ivy.core) can change the system
app behaviour at any time.
- fail if parameter is not set via standard maven plugin mechanism

XIVY-3479 make the definition of a deployApp mandatory

---

src/main/java/ch/ivyteam/ivy/maven/DeployToEngineMojo.java
src/test/java/ch/ivyteam/ivy/maven/TestDeployToEngineMojo.java
src/test/java/ch/ivyteam/ivy/maven/TestDeployToRunningEngine.java

- SYSTEM is a bad default which only leads to confusion, nobody should
use the system app for custom workflows (ivy.core) can change the system
app behaviour at any time.
- fail if parameter is not set via standard maven plugin mechanism

XIVY-3479 make the definition of a deployApp mandatory >> backport for 8.0 LTS

---

Jenkinsfile
pom.xml

Already start to not deploy this to our internal artifactory.
No build should faiil at the moment. But as soon as we are going to increase the version in the projects to the next SNAPSHOT version, they will fail.
In this case we have to add sonatype snapshot repository.
We will do that on demand.

Never deploy to internal artifactory

---

src/main/java/ch/ivyteam/ivy/maven/AbstractProjectCompileMojo.java
src/main/java/ch/ivyteam/ivy/maven/engine/EngineClassLoaderFactory.java
src/test/java/ch/ivyteam/ivy/maven/TestLoggerIntegration.java

- added test that fail with log warnings 'non resolvable slf4j' which
indicate a version conflict between the resolved maven plugin
dependencies and the api used by the Axon.ivy Engine.

XIVY-3441 fix: slf4j version mismatch disables engine logs

---

Jenkinsfile
pom.xml

Build: https://jenkins.ivyteam.io/job/project-build-plugin/job/feature%252FXIVY-3138-fix-master-after-renaming/
So far seems to be the only thing that got lost
- **8.0** is now the new **master**
- old **master** is now **legacy** branch (I would keep that branch alive for the time being, at least until we are sure everything works properly)

XIVY-3138 Define maven compiler source level for sonar

---

src/main/java/ch/ivyteam/ivy/maven/SetupIvyTestPropertiesMojo.java
src/main/java/ch/ivyteam/ivy/maven/util/MavenRuntime.java

- local projects are up to date and never dated repo artifacts
- local projects are available even when not packed: e.g. 'mvn clean
test'
- local projects (non IAR) are currently easier to deploy for
BpmExecTests.

XIVY-3565 prefer local reactor projects over IAR deps

---

src/main/java/ch/ivyteam/ivy/maven/IarPackagingMojo.java
src/test/java/ch/ivyteam/ivy/maven/TestIarPackagingMojo.java

There is no need to escape / (slashes) in a `regexp` file
pattern for maven filesets. Because there is some special
escaping by maven plexus that those regular expressions
are platform independent.

XIVY-3449 Use proper regex expression for exclude fileset

---

src/main/java/ch/ivyteam/ivy/maven/DeployToTestEngineMojo.java
src/test/java/ch/ivyteam/ivy/maven/TestDeployToTestEngineMojo.java

- otherwise runtime app will be created with a different, but compliant
name ... and therefore not be found with our webtest EngineUrl.

XIVY-494 fix: sanitize app name from non whitespace chars

---

src/main/java/ch/ivyteam/ivy/maven/engine/EngineModuleHints.java

- tomcat-catalina.jar seems to do some reflection work on stop, which we
mute since it only causes confusion for the plugin user.
Fixes errors as shown here:...
https://jenkins.ivyteam.io/job/ivy-project-demos/job/feature%252FXIVY-494-tstNoReflectWarns/6/consoleFull

XIVY-4413 fix reflect access warnings on engine-stop

---

src/main/java/ch/ivyteam/ivy/maven/engine/EngineModuleHints.java

- tomcat-catalina.jar seems to do some reflection work on stop, which we
mute since it only causes confusion for the plugin user.

XIVY-4413 fix reflect access warnings on engine-stop  ... LTS 8

---

src/main/java/ch/ivyteam/ivy/maven/bpm/test/IvyTestRuntime.java
src/test/java/ch/ivyteam/ivy/maven/TestSetupIvyTestPropertiesMojo.java

- avoid dirty workspaces for projects that stick to the old pattern,
where 'classes' dir is a child of the project, and not of the 'target'
as in normal maven projects.
see https://jira.axonivy.com/jira/browse/XIVY-4505

XIVY-4505 fix: 'ivyTestVm' occassionally not in 'target' dir

---

src/main/java/ch/ivyteam/ivy/maven/MavenDependencyMojo.java
src/main/java/ch/ivyteam/ivy/maven/util/MavenDependencies.java
src/main/java/ch/ivyteam/ivy/maven/util/MavenRuntime.java
src/test/java/ch/ivyteam/ivy/maven/TestMavenDependencyMojo.java

- do not pack deps which involve another 'iar' project.
- but give me the full artifact dependency tree for my local declared
deps.
also fixed: local reactor project dependencies win over declarations
from local repository (installed) projects.

XIVY-5531 pack only-local dependencies: but include transient

---

README.md
src/main/java/ch/ivyteam/ivy/maven/AbstractEngineMojo.java

Should fix build which uses the default version of the project-build-plugin for the right engine (e.g cockpit)

Raise default version to 9.4.0

---

src/main/java/ch/ivyteam/ivy/maven/util/MavenDependencies.java

- project directories from the reactor can't be packed into
/lib/mvn-deps ... so we resolve a JAR at any rate. either from the .m2
repo or the current reactor.

XIVY-8025 fix: favour repo or reactor built jar over reactor-dir

---

pom.xml
src/main/java/ch/ivyteam/ivy/maven/AbstractEngineMojo.java

- simplify the usage of the latest 10.0.3 engine APIs; here in particular, the new OAuth2 rest URI creators

XIVY-5608 raise default ivy-version to 10.0.3

---

src/main/java/ch/ivyteam/ivy/maven/engine/download/URLEngineDownloader.java
src/test/java/ch/ivyteam/ivy/maven/TestInstallEngineMojo.java

- we can no longer simulate file:// downloads, but need a real URI

XIVY-10909 adjust tests: use http-mock server to comply Http-Client

---

pom.xml

This reverts commit 7404af07935216863dd5d9ace5db16d2ae6a659e.

Revert "Bump maven-filtering from 3.2.0 to 3.3.1" > fix engine-cockpit build

---

pom.xml

This reverts commit ef53a017bb66a874e8a5c51b618003dd6a26c6c6.

Revert "Bump commons-io from 2.11.0 to 2.12.0"

---

pom.xml

- publish the latest snapshot doc
... snapshots docs from master were no longer published, now it works again
http://axonivy.github.io/project-build-plugin/snapshot/11.3/index.html

XIVY-13820 fix: allow github-site deployment for snapshots on 'master'

---

build/release/Jenkinsfile

official release were no longer run with docs: 
https://github.com/axonivy/project-build-plugin/blob/gh-pages/release/
did it manually back in time ...but with this change it should work again
https://jenkins.ivyteam.io/job/project-build-plugin/job/doc113/6/

XIVY-13820 fix: always deploy docs for public releases

---

pom.xml
src/site/site.xml

re-invent the feature dropped with https://github.com/axonivy/project-build-plugin/pull/208/commits/82daa6abff4f0abd688937aebcf5e1344a1102b0 ...where I wasn't mentioned :man_shrugging: 
nowadays I don't see a big problem in maintaining these properties.

XIVY-13820 fix: snapshots no linking official docs

---

pom.xml

do not work with the default tag format 'project-build-plugin-11.3.0' but use semantic 'v11.3.0'
- maven-release-plugin config in ossrhDeploy profile is inactive during maven-release-plugin:prepare runs
- I think since it's run in an own maven cycle à  la maven-invoker.
fixed ruN:

XIVY-13820 fix: tagNameFormat not semantic

---

pom.xml

- maven-release-plugin config in ossrhDeploy profile is inactive during maven-release-plugin:prepare runs

XIVY-13820 fix: tagNameFormat not semantic > R11.3

---

pom.xml

- maven-release-plugin config in ossrhDeploy profile is inactive during maven-release-plugin:prepare runs

XIVY-13820 fix: tagNameFormat not semantic > R10

---

src/test/java/ch/ivyteam/ivy/maven/TestDeployToRunningEngine.java

the problem was 100% reproducible also on my node: by blocking the default engine port 8080.
the test replaces the original System.out stream, and therefore we shortly need to re-stablish the real system.out, in order to capture the port/engine-url ..

Stabilize8

---

Jenkinsfile
pom.xml
src/main/java/ch/ivyteam/ivy/maven/engine/EngineClassLoaderFactory.java
src/main/java/ch/ivyteam/ivy/maven/engine/EngineControl.java
src/main/java/ch/ivyteam/ivy/maven/engine/download/URLEngineDownloader.java
src/main/java/ch/ivyteam/ivy/maven/util/MavenDependencies.java
src/test/java/ch/ivyteam/ivy/maven/BaseEngineProjectMojoTest.java
src/test/java/ch/ivyteam/ivy/maven/TestInstallEngineMojo.java

- Enable deprecation warnings in build
- Use Java Compiler recorder intead of ECJ

Fix deprecation warnings

---

pom.xml
src/main/java/ch/ivyteam/ivy/maven/compile/AbstractEngineInstanceMojo.java
src/main/java/ch/ivyteam/ivy/maven/engine/EngineClassLoaderFactory.java
src/test/java/ch/ivyteam/ivy/maven/compile/CompileMojoRule.java

I think it's time to move on.
Maven 3.9 is now also bundled as part of M2E. 
Should also fix security issues:
https://github.com/axonivy/project-build-plugin/security/dependabot

XIVY-14570 Upgrade to Maven 3.9

---

pom.xml

Otherwise Path can not injected. Maybe 3.9.7 or 3.9.8 is required.

Raise minimal required maven version to 3.9.6

---

src/main/java/ch/ivyteam/ivy/maven/InstallEngineMojo.java
src/main/java/ch/ivyteam/ivy/maven/MavenDependencyCleanupMojo.java
src/main/java/ch/ivyteam/ivy/maven/ShareEngineCoreClasspathMojo.java
src/main/java/ch/ivyteam/ivy/maven/compile/AbstractEngineInstanceMojo.java
src/main/java/ch/ivyteam/ivy/maven/deploy/AbstractDeployMojo.java
src/main/java/ch/ivyteam/ivy/maven/deploy/DeployToEngineMojo.java
src/main/java/ch/ivyteam/ivy/maven/deploy/DeployToTestEngineMojo.java
src/main/java/ch/ivyteam/ivy/maven/engine/EngineClassLoaderFactory.java
src/main/java/ch/ivyteam/ivy/maven/engine/EngineControl.java
src/main/java/ch/ivyteam/ivy/maven/engine/EngineMojoContext.java
src/main/java/ch/ivyteam/ivy/maven/engine/MavenProjectBuilderProxy.java
src/main/java/ch/ivyteam/ivy/maven/engine/deploy/DeploymentOptionsFileFactory.java
src/main/java/ch/ivyteam/ivy/maven/engine/deploy/dir/FileDeployer.java
src/main/java/ch/ivyteam/ivy/maven/engine/deploy/dir/FileLogForwarder.java
src/main/java/ch/ivyteam/ivy/maven/util/PathUtils.java
src/test/java/ch/ivyteam/ivy/maven/BaseEngineProjectMojoTest.java
src/test/java/ch/ivyteam/ivy/maven/ProjectMojoRule.java
src/test/java/ch/ivyteam/ivy/maven/TestIarPackagingMojo.java
src/test/java/ch/ivyteam/ivy/maven/TestInstallEngineMojo.java
src/test/java/ch/ivyteam/ivy/maven/TestShareEngineClasspathMojo.java
src/test/java/ch/ivyteam/ivy/maven/compile/TestCompileProjectMojo.java
src/test/java/ch/ivyteam/ivy/maven/deploy/TestDeployToEngineMojo.java
src/test/java/ch/ivyteam/ivy/maven/util/TestPathUtils.java

Remove most of commons.io usages
- java.nio provides good enough API's to to basic file operations
- our code mostly uses java.nio now which makes it more simple
- less dependencies to 3rd parties  which needs to be updated
- FileAlternateObserver still left

Remove most of commons.io usages

---

build/windows/Jenkinsfile

Do not mark build as unstable if tests are failing, because
there are some tests which do not work on windows.

Introduce a windows ci test pipeline to get early feedback about windows problems

---

src/test/java/ch/ivyteam/ivy/maven/test/TestStartEngine.java

I wanted to add a windows ci pipeline. At the moment not possible because some tests are killing an Axon Ivy Engine with SIGKILL. This prevents the Axon Ivy Engine from stoping the bundled Elasticsearch Service, which than makes it impossible to clean the engine directory.
Seems that it is not possible with commons.cli to gracefully stop a service. I will need first to use the new Java Process API to manage the Axon Ivy Engine Process. This will also eliminate some maven warnings because the process is killed with SIGKILL.

Make two tests also working on windows

---

pom.xml

otherwise goals using 'Path' parameter won't work on Windows and MacOS:
octopus and also @ivy-lmu were not able to build with 3.9.6 ... let's be fair and require 3.9.8

document minimal required 3.9.8

---

src/main/java/ch/ivyteam/ivy/maven/AbstractEngineMojo.java

I'll raise the project-build-plugin later. But with this change our build integration should work again.

Search by default a LTS 12 engine

---

Dockerfile

fix the release pipeline that fails at the end when instructed to push releases to github.
the ssh-agent is required as binary: see evidence that this works here https://jenkins.ivyteam.io/view/scrum-master/job/project-build-plugin_release/job/fixReleasePipe/

fix build: add ssh-agent for authorized pushes using GH

---

Jenkinsfile
build/release/Jenkinsfile
pom.xml

first approach that works without e-git; here to gather (your :wink: ) early feedback @alexsuter

Deploy github site using maven-scm-publish plugin :building_construction: 

---

.github/workflows/draft-publisher.yml
.github/workflows/release-drafter.yml
.github/workflows/tag-publisher.yml
README.md

- automatically publish new releases on new tags being created with semantic versions (v0.0.0)
- separate release/trains via 'commitish' without actually requiring multiple drafter templates

automate release-drafter publishing :newspaper_roll:  > R12

---

src/main/java/ch/ivyteam/ivy/maven/validate/ValidateMojo.java
src/main/resources/META-INF/plexus/components.xml
src/test/java/ch/ivyteam/ivy/maven/validate/TestValidateMojo.java

Tested with different project-build-plugin versions (12.0.1 and 12.0.2). Result in error message:
```log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] workflow-demos                                                     [iar]
[INFO] workflow-demos-test                               [iar-integration-test]
[INFO] workflow-demos-product                                             [pom]
[INFO] workflow-modules                                                   [pom]
[INFO]
[INFO] ------------------< com.axonivy.demo:workflow-demos >-------------------
[INFO] Building workflow-demos 12.0.2-SNAPSHOT                            [1/4]
[INFO]   from workflow-demos/pom.xml
[INFO] --------------------------------[ iar …
```

 XIVY-10541 Detect different plugin versions

---

src/main/java/ch/ivyteam/ivy/maven/validate/ValidateMojo.java
src/main/resources/META-INF/plexus/components.xml
src/site/apt/lifecycle.apt.vm
src/test/java/ch/ivyteam/ivy/maven/validate/TestValidateMojo.java

demo-projects build output:
```
[INFO] --- ivy:10.0.17-SNAPSHOT:validate (default-validate) @ workflow-demos ---
[ERROR] Several versions of project-build-plugins are configured [10.0.17-SNAPSHOT, 10.0.6]:
10.0.17-SNAPSHOT -> [workflow-demos]
10.0.6 -> [html-dialog-demos, html-dialog-demos-test, error-handling-demos, quick-start-tutorial, rule-engine-demos, rule-engine-demos-test, workflow-demos-test, connectivity-demos, connectivity-demos-test]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ivy-project-modules 10.0.3-SNAPSHOT:
[INFO]
[INFO] html-dialog-demos .................................. SUCCESS [  4.083 s]
[INFO] html-dialog-demos-test ............................. SUCCESS [  0.756 s]
[INFO] html-dialog-demos-product …
```

XIVY-10541 Validate that only one project-build-plugin version is in the reactor

---

Jenkinsfile
pom.xml

- Generate sbom
- Upload it to dtrack
- This will automatically attach the json as part of the official release
```
--- install:3.1.2:install (default-install) @ project-build-plugin ---
[INFO] Installing /home/alex/git/project-build-plugin/pom.xml to /home/alex/.m2/repository/com/axonivy/ivy/ci/project-build-plugin/13.1.0-SNAPSHOT/project-build-plugin-13.1.0-SNAPSHOT.pom
[INFO] Installing /home/alex/git/project-build-plugin/target/project-build-plugin-13.1.0-SNAPSHOT.jar to /home/alex/.m2/repository/com/axonivy/ivy/ci/project-build-plugin/13.1.0-SNAPSHOT/project-build-plugin-13.1.0-SNAPSHOT.jar
[INFO] Installing /home/alex/git/project-build-plugin/target/bom.json to /home/alex/.m2/repository/com/axonivy/ivy/ci/project-build-plugin/13.1.0-SNAPSHOT/project-build-plugin-13.1.0-SNAPSHOT-cyclo …
```

Generate sbom, upload it to dtrack and provide it via maven repository

---

.github/renovate.json

seems like we can't inherit them from our global renovate-config

renovat: re-state base-branches

---

.github/renovate.json

- build > maven plugins
- compile > dependencies

renovate: select dep-type rather than names

---

src/test/java/ch/ivyteam/ivy/maven/test/TestStartEngine.java

- however; it's not the job of the project-build-plugin validate the engine performance

stabilize: stopping a running engine seems to get slower

---

.github/renovate.json

- at least 2 leading digits: we only maintain 10.0 and newer

dynamic pattern to cover new release branches

---

.github/workflows/tag-publisher.yml

auto-publishing of our 13.1.0 release failed, this time due to the release-drafter :man_shrugging: 
https://github.com/axonivy/project-build-plugin/actions/runs/15047692194

fix: auto release publisher failed due to broken workflow reference

---

pom.xml
src/main/java/ch/ivyteam/ivy/maven/engine/EngineClassLoaderFactory.java
src/main/resources-filtered/versions.properties

common renovate blocker of the past ... upgrades of slf4j never came for free, as the constant in the code had to be updated manually

renovate; read slf4j version from properties

---

pom.xml
src/main/java/ch/ivyteam/ivy/maven/engine/Slf4jSimpleEngineProperties.java
src/test/java/ch/ivyteam/ivy/maven/TestSlf4jWarningConfiguration.java
src/test/java/ch/ivyteam/ivy/maven/compile/TestCompileProjectMojo.java
src/test/resources/base/processes/myWebService.p.json

enables our configuration for `[WARNING]` prefixed brackets, just like maven does, .... while the default of slf4j is `[WARN]`.
since slf4j 2.x half-way removed that feature, we have to downgrade to 1.7.x:
- maven CLI also uses slf4j.simpl 1.7
- Nevertheless, I'll try to [discuss](https://github.com/qos-ch/slf4j/pull/463) the re-introduction of the 'warningString' configuration on the slf4j repos. Since the configuration values are still [documented](https://github.com/qos-ch/slf4j/blob/183aaa507040ce6c61f70762c13e7d11aa4fd54e/slf4j-simple/src/main/java/org/slf4j/simple/SimpleLogger.java#L203C32-L203C53) and in the code, but they are no longer interpreted :shrug:

XIVY-16828 Process issues not reported as [WARNING]

---

pom.xml

I changed the selenium-test of release/10 to work with the latest available 10.0.18-SNAPSHOT and it did no longer work due to the absence of the plexus-sec-dispatcher. See https://github.com/axonivy/core/pull/9153
and https://jenkins.ivyteam.io/job/core_test-selenium/job/useSnap/3
I think we lost it by raising a peer dependency, which was importing sec-dispatcher, at any rate was the last official release 10.0.17 still ok.
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:51 min
[INFO] Finished at: 2025-06-06T16:54:55+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal …
```

fix: deploy-to-engine mojo fails due to missing plexus-sec-dispatcher
